### ISSUE TITLE
Bug an scroll slider in demo

### ISSUE THREAD

**Issue by hoangnam714** [DominikButz/MinimizableView#11]
Hello
I see some problems in your project, the slider doesn't work on iOS 17.5.1, I tested it on a real device, perhaps some gesture is blocking the entire UI, are you experiencing the same thing as me?
In my real project, except for buttons, everything related to touch and swipe is blocked

**Comment by DominikButz** [comment]
Hi, that's correct. However, I currently don't know how to fix this. If you have a suggestion, please let me know. The code is open source after all.  The culprit is this modifier in the file MinimizableView.swift: 

               .gesture(DragGesture(minimumDistance: settings.minimumDragDistance,  coordinateSpace: .global)
                            .onChanged(self.dragOnChanged)
                            .updating(dragOffset, body:self.dragUpdating)
                            .onEnded(self.dragOnEnded))

If you fork it and then pull the repo from your account, you can modify the code by commenting it out. you will see that it works afterwards... however, without this modifier, dragging down to collapse and dragging up to expand won't work any more.

**Comment by DominikButz** [comment]
... an alternative might be to use the .sheet modifier with .presentationDetents modifier. It's also possible now to deactivate dismissal through swipe down gesture.

**Comment by DominikButz** [comment]
I think I found an easy fix. in the mini settings, just add the property "minimumDragDistance" and set it to a value greater than 0. even 1 seems to work.

`
             .minimizableView(content: {ContentExample(animationNamespaceId: self.namespace)},
                  compactView: {
                    return EmptyView()
                     // put CompactViewExample() here to see the a different approach for the compact view
                }, backgroundView: {
                    self.backgroundView()},
                    dragOffset: $dragOffset,
                    dragUpdating: { (value, state, _) in
                        state = value.translation
                        self.dragUpdated(value: value)
                }, dragOnChanged: { (value) in
                    // unused
                },
                    dragOnEnded: { (value) in
                    self.dragOnEnded(value: value)
                }, minimizedBottomMargin: self.miniViewBottomMargin, settings: MiniSettings(minimizedHeight: 75, minimumDragDistance: 1))
                .environmentObject(self.miniHandler)
`
