### ISSUE TITLE
hello,Is it possible to implement "DragGesture().updating(...)" within the configuration?

### ISSUE THREAD

**Issue by wxyjay** [DominikButz/MinimizableView#5]
I'm using your library in my project and it's currently working fine on mobile.
I need to implement an effect now, but I need to update the value of the sliding state object in "DragGesture() .updating($...)", I would like to ask if there is a way to extend your DragGesture configuration?

like⬇️
                .gesture(
                DragGesture(minimumDistance: 0)
                  .updating($dynamics) { value, state, _ in
                      if state.translation > 0 {
                          state.delta = value.translation.height - state.translation
                          state.translation = value.translation.height
                      }
                      else {
                          state.translation = value.translation.height
                      }
                  }
                  .onChanged({ value in
                    ...
                  })
                  .onEnded({ value in
                    ...
                  })

                )

**Comment by DominikButz** [comment]
Thanks for the proposal.

You mean like this?

`  

 @GestureState var dragOffset = CGSize.zero

var body: some View { 
               .....
                .minimizableView(content: {ContentExample(animationNamespaceId: self.namespace)},
                  compactView: {
                    EmptyView()  // replace EmptyView() by CompactViewExample() to see the a different approach for the compact view
                }, backgroundView: {
                    self.backgroundView()
                }, dragOnChanged: { (value) in
                    self.dragOnChanged(value: value)
                }, gestureState: $dragOffset,                      
                    dragUpdatingBody: { (value, state, _) in
                    state = value.translation
                    print(state)
                },
                    dragOnEnded: { (value) in
                    self.dragOnEnded(value: value)
                }, geometry: proxy, settings: MiniSettings(minimizedHeight: 80))
                .environmentObject(self.miniHandler)

}
`

**Comment by wxyjay** [comment]
Yes this is exactly what I need, if possible, I hope you can add this configuration.

DragGesture .updating(){ **value, state** } ⬅️ These two values are what I need to get.

thank you very much! ! !

**Comment by wxyjay** [comment]
In addition, I found three small problems during my use. If it doesn't take up too much time for you, I hope you can check it out.
1. At the beginning of scrolling down the expansion content, it will freeze for about 0.1 to 0.2 seconds. I'm new to swiftUI, I checked some sources, maybe it has something to do with *DragGesture(minimumDistance: here)*?

2. Swiping down on the extended content will drop frames, which works fine on devices with non-120Hz refresh rate, but has this problem on 13Pro & 13PM. ps: I now replace self.miniHandler.draggedOffsetY = value.translation.height with withAnimation(.spring(response: 0)) {
                 self.miniHandler.draggedOffsetY = value.translation.height
               } works, but it stutters again on non-120Hz devices...I also checked some sources. I don't know if it can be solved by using PanGesture?

3. There will be an intuitive display in the second video, please check it out.

Device: iPhone13Pro & iPhone X
IOS version: 15.6
I took a video 👉 [Link](https://drive.google.com/drive/folders/1fcKDT20tLdzUikWJv-bOjTfEyC-Tut_5?usp=sharing)

Thank you for taking the time to read my question 🙏

**Comment by DominikButz** [comment]
Thanks for the input. I will implement the dragUpdating closure first. At first sight, it looks like calling the updating logic in the dragUpdating closure instead of the dragOnChange closure solves the delay problem that looks like the view is frozen for a fraction of a second. I need to do a few tests and then will release an update shortly.

**Comment by wxyjay** [comment]
Thanks, looking forward to your progress!

**Comment by DominikButz** [comment]
updated to version 2.3. In the example project, try dragging down on the photo of the dog and above the dog. It seems it only stutters when you start the drag above it. I have moved the updating logic into the dragUpdating closure. 
As to the other issues, I need to check them out later. However, don't hesitate to fork the project and submit a pull request in the meantime.

**Comment by wxyjay** [comment]
OK I will test it now, thanks

**Comment by wxyjay** [comment]
After I updated to version 2.3, the response speed of the swipe gesture has been greatly improved, and a new problem has appeared here.
My expand player view has a lyric view, which is a swipeable view composed of List. After updating to version 2.3; the swipe gesture of the parent view (expand view) will prevent the swipe gesture and tap gesture of the List, which was normal before Yes, I'm still trying to figure it out...

**Comment by DominikButz** [comment]
Can you send a video that shows the problem? I can only see that the view underneath the miniView is a list but the content view of the miniView has no list - at least in your earlier video it is not visible.

**Comment by DominikButz** [comment]
Version 2.3.1 fixes the simultaneous drag & pan gesture bug. Thanks for the hint!

**Comment by DominikButz** [comment]
Version 2.3.2 added minimumDragDistance to settings. if you set this > 0, e.g. 10, this will fix the frozen List view problem.

**Comment by DominikButz** [comment]
updated to version 2.3.3 - there was a weird bug that made the background transition in from above ...

**Comment by DominikButz** [comment]
Closed

**Comment by wxyjay** [comment]
> Closed

OK, thank you for your effort. I test it now. If there are any follow-up questions or suggestions, I will send them to you as soon as possible.
